apiVersion: v1
kind: Service
metadata:
  name: cpservice-annotator-service
  namespace: cpservice-annotator-system
  labels:
    app: cpservice-annotator
spec:
  ports:
  - port: 8443
    targetPort: 8443
  selector:
    app: cpservice-annotator
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: cpservice-annotator-configuration
  annotations:
    cert-manager.io/inject-ca-from: cpservice-annotator-system/selfsigned-cert
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: cpservice-annotator-service  
      path: /mutate
      port: 8443
      namespace: cpservice-annotator-system
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
  failurePolicy: Fail
  name: mpod.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - services