apiVersion: v1
kind: Namespace
metadata:
  name: cpservice-annotator-system
spec: {}
status: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: cpservice-annotator-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: cpservice-annotator-system
spec:
  secretName: cpservice-annotator-certs
  dnsNames:
    - cpservice-annotator-service.cpservice-annotator-system.svc
    - cpservice-annotator-service.cpservice-annotator-system.svc.cluster.local
  issuerRef:
    name: selfsigned-issuer