#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")


#@overlay/match by=overlay.subset({"kind":"Cluster"})
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
#@ if data.values.AVI_CP_SETTING_NAME:
metadata:
  annotations: 
#@overlay/match missing_ok=True
    cpservicemutate.field.vmware.com/aviinfrasetting: #@ data.values.AVI_CP_SETTING_NAME

#@ end
