#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")


#@ def rule_matcher():
apiGroups:
- ako.vmware.com
#@ end

#@overlay/match by=overlay.subset({"kind":"ClusterRole","metadata":{"name":"ako-cr"}})
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
rules:
  #@overlay/match by=overlay.subset(rule_matcher())
  -
    #@overlay/match missing_ok=True
    resources:
    - aviinfrasettings
    - aviinfrasettings/status
